-- AlterTable
ALTER TABLE "Wallet" ALTER COLUMN "balance" SET DEFAULT 0,
ALTER COLUMN "balance" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "WalletEntry" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;
