import { ApiProperty } from "@nestjs/swagger";
import { IsString } from "class-validator";

export class ExpoTokenDto {
  @ApiProperty({ description: 'Expo push notification token generated by the device'})
  @IsString()
  token: string
}